export const lightTheme = {
  background: "#FFFFFF",
  primary: "#000",
  secondary: "#888",
  alternate: "#3BACE3",
  accentBackground: "#f8f8f8",
  textPrimary: "#000000",
  textSecondary: "#737373",
  textMatch: "#fff",
  buttonBackground: "#3BACE3",
  buttonText: "#fff",
  inactive: "#e8e8e8",
  icon: "#000",
  tabIcon: "#3BACE3",
  inactiveTabIcon: "#808080",
  error: "red",
};

export const darkTheme = {
  background: "#121212",
  primary: "#fff",
  secondary: "#545454",
  alternate: "#3BACE3",
  accentBackground: "#1a1a1a",
  textPrimary: "#FFFFFF",
  textSecondary: "#888",
  textMatch: "#121212",
  buttonBackground: "#3BACE3",
  buttonText: "#fff",
  inactive: "white",
  icon: "#fff",
  tabIcon: "#3BACE3",
  inactiveTabIcon: "#808080",
  error: "red",
};
